package ru.voskhod.smev.message_exchange_service_client.impl;

import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.AttachmentContentList;
import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.AttachmentHeaderList;
import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.RefAttachmentHeaderList;

public final class InAttachments {

    public final AttachmentHeaderList headerList;
    public final AttachmentContentList contentList;
    public final RefAttachmentHeaderList fsAttachmentsList;

    InAttachments(AttachmentHeaderList headerList, AttachmentContentList contentList, RefAttachmentHeaderList fsAttachmentsList) {
        this.headerList = headerList;
        this.contentList = contentList;
        this.fsAttachmentsList = fsAttachmentsList;
    }
}
