package ru.voskhod.smev.message_exchange_service_client.impl;

import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.AttachmentContentType;
import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.AttachmentHeaderType;
import ru.voskhod.smev.message_exchange_service_client.OutAttachment;
import ru.voskhod.smev.message_exchange_service_client.SomeMimeTypes;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public final class SmallOutAttachment implements OutAttachment {

    private final AttachmentHeaderType header;
    private final AttachmentContentType attachment;

    public SmallOutAttachment(AttachmentHeaderType header, AttachmentContentType attachment) {
        this.header = header;
        this.attachment = attachment;
    }

    public String getName() {
        return attachment.getId() + SomeMimeTypes.guessFileExtension(getMimeType());
    }

    public String getMimeType() {
        return header == null ? null : header.getMimeType();
    }

    public byte[] getSignature() {
        return header == null ? null : header.getSignaturePKCS7();
    }

    public Content getContent() {
        return new SmallContent();
    }

    private final class SmallContent implements Content {

        private volatile boolean cancelled = false;

        public boolean retrieve(OutputStream output) throws IOException {
            try (InputStream is = attachment.getContent().getInputStream()) {
                byte[] buf = new byte[8192];
                while (!cancelled) {
                    int read = is.read(buf);
                    if (read < 0)
                        return true;
                    output.write(buf, 0, read);
                }
                return false;
            }
        }

        public void cancel() {
            cancelled = true;
        }
    }
}
