package ru.voskhod.smev.message_exchange_service_client.datatypes;

import ru.voskhod.smev.message_exchange.autogenerated.types.basic.v1_1.XMLDSigSignatureType;
import ru.voskhod.smev.message_exchange.autogenerated.types.v1_1.MessageMetadata;

public class MessageMetaDataAndSMEVSignature {

    private final MessageMetadata messageMetadata;
    private final XMLDSigSignatureType smevSignature;

    public MessageMetaDataAndSMEVSignature(MessageMetadata messageMetadata, XMLDSigSignatureType smevSignature) {
        this.messageMetadata = messageMetadata;
        this.smevSignature = smevSignature;
    }

    public MessageMetadata getMessageMetadata() {
        return messageMetadata;
    }

    public XMLDSigSignatureType getSmevSignature() {
        return smevSignature;
    }
}
